?start: expr
?expr: string | raw_string | integer | sexpr | name | quoted
INTEGER: /[-+]?[0-9]+/
integer: INTEGER
STRING: /(?!\"\"\")"(\\\"|[^"]|\n)*?\"/
string: STRING
RAW_STRING: /\"\"\"(\\\"\"\"|.|\n)*?\"\"\"/
raw_string: RAW_STRING
NAME: /(?![-+]?[0-9])[-_$@:+*\/a-zA-Z0-9.#<>]+/
name: NAME

quoted: "&" expr

// This LEFT_BRACKET captures the position of the s-expression for debugging
LEFT_PAREN: "("

sexpr: LEFT_PAREN expr+ ")"
COMMENT: /;.*\n/
%import common.WS
%ignore WS
%ignore COMMENT