?start: type

?type: prefix_type | union_type
?prefix_type: function_type | primitive_type | quoted_type | sexpr_type

_LAMBDA : "λ" | "^"
function_type: "(" _LAMBDA type* ["..." type] "." type ")"
!primitive_type: "any"
               | "never"
               | "int"
               | "str"
               | "inline"
               | "block"
union_type: (prefix_type "|")+ prefix_type
quoted_type: "&" "[" type "]"
sexpr_type: "(" type+ ")"

%import common.WS
%ignore WS